### ISSUE TITLE
file not found when searching for libclang

### ISSUE THREAD

**Issue by niosus** [niosus/test-complete-plugin#1]
@pl-ca reported:

When I launch ST3 after installing the plug-in I get an error related to some file not found. Am I missing something?

```
reloading plugin test-complete-plugin.script
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Pierre-Louis\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\script.py", line 14, in <module>
    clang_dir = ClangUtils.find_libclang_dir("clang++")
  File "C:\Users\Pierre-Louis\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\clang\utils.py", line 62, in find_libclang_dir
    get_library_path_cmd).decode('utf8').strip()
  File "./python3.3/subprocess.py", line 576, in check_output
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

**Comment by niosus** [comment]
Ok, I will try to find out what can be wrong. Until then, could you try to run the script from Powershell, @pl-ca?

**Comment by niosus** [comment]
Any news on that, @pl-ca? Have you had the time to try the script from powershell?

**Comment by royce002** [comment]
I am running into the same issue, how can i try the script from powershell?

**Comment by niosus** [comment]
@royce002 you should just navigate to the folder where the script lies using powershell and call something like `python.exe script.py`. This should be enough.

**Comment by pl-ca** [comment]
Sorry for the delay @niosus. I ran through PowerShell with python 2.7, and got this error

```
Traceback (most recent call last):
  File ".\script.py", line 14, in <module>
    clang_dir = ClangUtils.find_libclang_dir("clang++")
  File "C:\Users\Pierre-Louis\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\clang\utils.py", line 62, in find_libclang_dir
    get_library_path_cmd).decode('utf8').strip()
  File "C:\Python27\lib\subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] Le fichier spΘcifiΘ est introuvable
```

The french error at the end means file not found.

**Comment by niosus** [comment]
Hm, I don't know what happens if you run it with python 2. Can you try with any python 3? :)

**Comment by niosus** [comment]
Closing for now. One discussion I guess is enough at this point
